baseURL: https://www.alphapivita.gr/
metaDataFormat: yaml

## Debug
enableMissingTranslationPlaceholders: true

## Misc display settings
# pygmentsCodefences: true
# pygmentsUseClasses: true
pluralizeListTitles: false
footnoteReturnLinkContents: "*"

## Menu settings
# sectionPagesMenu: main # see https://gohugo.io/templates/menu-templates/#section-menu-for-lazy-bloggers


## Active Theme
theme: onionskin

## Taxonomies settings
taxonomies:
  category: categories
  tag: tags
  series: series # opengraph default partial may fail without this

frontmatter:
  date:
    - :filename
    - :default

## Permalink settings
relativeURLs: true
permalinks:
  projects: /:section/:slug/
  announcements: /:section/:year/:slug/
  blog: /:section/:year/:month/:day/:slug/

## Language specific settings
copyright: |
  © 2019 Open Children’s Library
defaultContentLanguage: el
languages:
  en:
    weight: 2
    languageName: en
    languageCode: en
    title: Open Children’s Library
    params:
      # description: Personal website of …
  el:
    weight: 1
    languageName: ελ
    languageCode: el
    title: Ανοικτή Παιδική Βιβλιοθήκη
    logo: '<span class="mono"><span style="color: rgb(239, 118, 122)">Ανοικτή</span> <span style="color: rgb(239, 184, 104)">Παιδική</span> <span style="color: rgb(29, 188, 180)">Βιβλιοθήκη</span></span>'
    copyright: |
      © 2019 «Παιδική Βιβλιοθήκη»<br> Σωματείο για την πολιτισμική παρέμβαση και<br> την ενίσχυση της καθολικής πρόσβασης του παιδιού στο έντυπο και ψηφιακό βιβλίο.<br><!--<a href="https://creativecommons.org/licenses/by-sa/3.0/deed.el">Creative&nbsp;Commons&nbsp;BY-SA</a>-->
    params:
      # description: Personal website of …
  ur:
    languageName: اُردُو
    languageCode: ur
    title: Open Children’s Library
    weight: 3
    params:
      locale: ur
      languageDir: rtl
  fa:
    languageName: فارسی
    languageCode: fa
    title: Open Children’s Library
    weight: 4
    params:
      locale: fa
      languageDir: rtl

## Custom parameters
params:
  theme: white sans
  menu_main: false # Display main menu, default is true
  # menu_footer: false # Display footer menu, default is true
  # show_share: false # Social sharing buttons, default is true
  show_meta: false # Post metadata display, default is true
  # show_social: false # Display social menu in footer, default is true
  show_ui: false # Display UI features, default is true
  # show_comments: false # Dislay comments, default is true
  # search: true # Enable search, currently unavailable
  # languageDir: rtl # Language direction, default is none
  # logo: "" # Custom header, default is none
  date_format: "02/01/2006"
  social:
    - name: facebook
      link: https://www.facebook.com/alphapivita/
      icon: f
    - name: instagram
      link: https://www.instagram.com/alphapivita/
      icon: m
    - name: email
      link: mailto:info@alphapivita.gr
      icon: e

## Services settings
# googleAnalytics: # Google Analytics ID, see https://gohugo.io/templates/internal/
# disqusShortname: # Disqus ID, see https://gohugo.io/templates/internal/

## Services privacy settings, see https://gohugo.io/about/hugo-and-gdpr/
privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: true
  instagram:
    disable: false
    simple: true
  twitter:
    disable: false
    enableDNT: true
    simple: true
  vimeo:
    disable: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true