baseURL: https://www.alphapivita.gr/
metaDataFormat: yaml

## Debug
enableMissingTranslationPlaceholders: true

## Misc display settings
# pygmentsCodefences: true
# pygmentsUseClasses: true
pluralizeListTitles: false
footnoteReturnLinkContents: "*"


## Active Theme
theme: onion

## Post Summaries
summaryLength: 12

## Taxonomies settings
taxonomies:
  category: categories
  tag: tags
  series: series # opengraph default partial may fail without this

frontmatter:
  date:
    - :filename
    - :default

## Permalink settings
relativeURLs: true
permalinks:
  projects: /:section/:slug/
  announcements: /:section/:year/:slug/
  news: /:section/:year/:slug/
  blog: /:section/:year/:month/:day/:slug/

## Language specific settings
copyright: |
  © 2019 Children’s Open Library
defaultContentLanguage: el
languages:
  en:
    weight: 2
    languageName: English
    languageCode: en
    title: Children’s Open Library
    params:
  el:
    weight: 1
    languageName: Ελληνικά
    languageCode: el
    title: Ανοικτή Παιδική Βιβλιοθήκη
    logo: '<img src="../../assets/alphapivita_EL_rect_B.png" alt="Ανοικτή Παιδική Βιβλιοθήκη" width="350">'
    copyright: |
      © 2019-2021 «Παιδική Βιβλιοθήκη»<br> Σωματείο για την πολιτισμική παρέμβαση και<br> την ενίσχυση της καθολικής πρόσβασης του παιδιού στο έντυπο και ψηφιακό βιβλίο.<br><!--<a href="https://creativecommons.org/licenses/by-sa/3.0/deed.el">Creative&nbsp;Commons&nbsp;BY-SA</a>-->
    params:
  # ur:
  #   weight: 3
  #   languageName: اُردُو
  #   languageCode: ur
  #   title: Children’s Open Library
  #   params:
  #     locale: ur
  #     languageDir: rtl
  # fa:
  #   weight: 4
  #   languageName: فارسی
  #   languageCode: fa
  #   title: Children’s Open Library
  #   params:
  #     locale: fa
  #     languageDir: rtl
    menu:
      main:
      - name: contact
        weight: 10
        url: /epikoinonia/
      - name: community
        weight: 20
        url: /koinotita/
    #   - name: threeee
    #     weight: 30
    #     pre: '<span class="cta">'
    #     post: '</span>'
      footer:
      - name: terms-of-use
        weight: 10
        url: /terms-of-use/
      - name: privacy-policy
        weight: 20
        url: /privacy-policy/
      - name: statute
        weight: 30
        url: /katastatiko/

## Custom parameters
params:
  theme: theme-white font-sans
  menu_main: true # Display main menu, default is true
  menu_footer: true # Display footer menu, default is true
  # show_share: false # Social sharing buttons, default is true
  show_meta: false # Post metadata display, default is true
  # show_social: false # Display social menu in footer, default is true
  show_ui: false # Display UI features, default is true
  # show_comments: false # Dislay comments, default is true
  # search: true # Enable search, currently unavailable
  # languageDir: rtl # Language direction, default is none
  # logo: "" # Custom header, default is none
  date_format: 02/01/2006
  social:
    - name: facebook
      link: https://www.facebook.com/alphapivita/
      icon: f
    - name: instagram
      link: https://www.instagram.com/alphapivita/
      icon: m
    - name: email
      link: mailto:info@alphapivita.gr
      icon: e

## Services settings
# googleAnalytics: # Google Analytics ID, see https://gohugo.io/templates/internal/
# disqusShortname: # Disqus ID, see https://gohugo.io/templates/internal/

## Services privacy settings, see https://gohugo.io/about/hugo-and-gdpr/
privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: true
  instagram:
    disable: false
    simple: true
  twitter:
    disable: false
    enableDNT: true
    simple: true
  vimeo:
    disable: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

## goldmark markdown renderer settins
markup:
  goldmark:
    renderer:
      unsafe: true